import { MINUTES_PER_HOUR, HOURS_PER_DAY, BALANCE, COMMODITIES, MARKET_COMMODITIES, CARGO_COMMODITIES, COMMODITY_NAMES, COMMODITY_BASE_PRICES } from "./config/economy.js";
import { FACTIONS, DEFAULT_FACTION_RELATIONS, FACTION_INTERESTS, INFLUENCE_BASES, FACTION_ASK_TYPES, MAJOR_FACTIONS, GUILD_FACTIONS, GUILD_TIER_NAMES, GUILD_REQUIREMENTS } from "./config/factions.js";
import { PORT_TYPES } from "./config/ports.js";

export { MINUTES_PER_HOUR, HOURS_PER_DAY, BALANCE, COMMODITIES, MARKET_COMMODITIES, CARGO_COMMODITIES, COMMODITY_NAMES, COMMODITY_BASE_PRICES, FACTIONS, DEFAULT_FACTION_RELATIONS, FACTION_INTERESTS, INFLUENCE_BASES, FACTION_ASK_TYPES, MAJOR_FACTIONS, GUILD_FACTIONS, GUILD_TIER_NAMES, GUILD_REQUIREMENTS, PORT_TYPES };
export { SAVE_VERSION, SAVE_KEY, SAVE_KEY_LEGACY, SAVE_KEY_CLASSIC } from "./config/persistence.js";
export { COMMODITY_REGISTRY, getCommodityDef, getCommodityIdsByCategory, RAW_COMMODITIES, PROCESSED_COMMODITIES, MANUFACTURED_COMMODITIES, PULSE_COMMODITIES } from "./config/economy.js";
export { NPC_FINDABLE_PART_DEFS, NPC_FINDABLE_PARTS, DEBUG_MODE, CONTACT_SERVICE_LABELS, UI_LABELS, PLANET_TYPES, BUILDING_DEFS, UPGRADE_DEFS, CONTACT_DEFS, CAPTAIN_DEFS, ARCHETYPE_LABELS } from "./config/entities.js";
export { MISSION_TUNING } from './config/missions.js';
export { STARTER_PLAYER, STARTER_SHIP } from './config/player.js';
export { POLITICS } from './config/politics.js';
export { MAP_UI } from './config/ui.js';
export { PORT_DEFAULTS, STARFIELD, WORLDGEN_GEOMETRY, WORLDGEN_SPAWN } from './config/worldgen.js';
