export {
    CHAR_STATS,
    CHAR_DEFAULTS,
    STAT_BUY_CURVE,
    PLATFORM_TYPES,
    PLATFORM_PACKAGES,
    DEFAULT_PLATFORM_TYPE,
    LEGACY_PLATFORM_TYPE_MAP,
    normalisePlatformType,
    DEFAULT_EMPLOYER_LANE_ID,
    EMPLOYER_LANES,
    START_PACKAGES,
    ARCHETYPE_PRESETS,
    DEFAULT_BUILD_SPEC,
    DEBUG_FALLBACK_BUILD_SPEC,
    createStarterShipFromPlatform,
    getStarterCredits
} from './chargen.js';
