import { MARKET_BALANCE, TRADE_BALANCE, LOGISTICS_OBJECTIVE_BALANCE } from "../constants/marketBalance.js";
import { MARKET_COMMODITIES, COMMODITY_REGISTRY, getCommodityDef, getCommodityIdsByCategory, RAW_COMMODITIES, PROCESSED_COMMODITIES, MANUFACTURED_COMMODITIES, PULSE_COMMODITIES, CARGO_COMMODITIES, COMMODITY_NAMES, COMMODITY_BASE_PRICES } from "./economy/commodities.js";

export const MINUTES_PER_HOUR = 60;
export const HOURS_PER_DAY = 24;

export const BALANCE = {
    DAY_MINUTES: HOURS_PER_DAY * MINUTES_PER_HOUR,
    SIMULATION_TRACE_LIMIT: 160,
    DEFAULT_WAKE: 8 * MINUTES_PER_HOUR,
    DEFAULT_SLEEP: HOURS_PER_DAY * MINUTES_PER_HOUR,
    CAPTAIN_HOURLY_ACTION_CHANCE: 0.045,
    CAPTAIN_MISSION_INTEREST_THRESHOLD: 28,
    CAPTAIN_MISSION_TAKE_THRESHOLD: 55,
    DIALOGUE_LOCATE_ITEM: {
        BASE_SUCCESS_CHANCE: 0.45,
        FAVORED_PORT_SUCCESS_BONUS: 0.12,
        FAVORED_REGION_SUCCESS_BONUS: 0.08,
        RELATIONSHIP_TRUST_DIVISOR: 250,
        RELATIONSHIP_TRUST_MIN_BONUS: -0.08,
        RELATIONSHIP_TRUST_MAX_BONUS: 0.12,
        RELATIONSHIP_FAMILIARITY_DIVISOR: 400,
        RELATIONSHIP_FAMILIARITY_MAX_BONUS: 0.05,
        ATTEMPT_SUCCESS_BONUS: 0.04,
        ATTEMPT_SUCCESS_BONUS_CAP: 0.14,
        RARITY_SUCCESS_PENALTY: 0.22,
        PIRATE_THREAT_SUCCESS_PENALTY: 0.035,
        PIRATE_THREAT_SUCCESS_PENALTY_CAP: 0.24,
        MIN_SUCCESS_CHANCE: 0.08,
        MAX_SUCCESS_CHANCE: 0.92,
        RARITY_PRICE_MULTIPLIER: 0.55,
        PIRATE_THREAT_PRICE_MULTIPLIER: 0.035,
        PIRATE_THREAT_PRICE_MULTIPLIER_CAP: 0.25,
        FAVORED_PORT_PRICE_DISCOUNT: 0.06,
        FAVORED_REGION_PRICE_DISCOUNT: 0.03,
        RELATIONSHIP_DISCOUNT_DIVISOR: 400,
        RELATIONSHIP_DISCOUNT_MIN: 0.82,
        RELATIONSHIP_DISCOUNT_MAX: 1.08
    },
    ...TRADE_BALANCE,
    TRADE_ROUTE_BASE_COST: 1200,
    TRADE_ROUTE_INTERVAL_DAYS: 1,
    TRADE_ROUTE_BASE_AMOUNT: 12,
    TRADE_ROUTE: {
        DEFAULT_DELAY_DAYS: 1,
        DEFAULT_RELIABILITY: 50,
        PLAYER_START_RELIABILITY: 55,
        CAPTAIN_START_RELIABILITY: 52,
        CAPTAIN_MIN_AMOUNT: 6,
        CAPTAIN_DEFAULT_CARGO_CAPACITY: 60,
        CAPTAIN_CARGO_SHARE: 0.18,
        SETUP_HOP_COST: 140,
        SETUP_EFFECTIVE_SPAN_COST: 24,
        SETUP_RISK_COST: 130,
        PROFIT_SPREAD_FLOOR: 8,
        PROFIT_FLOOR: 25,
        PROFIT_MULTIPLIER: 0.38,
        PROFIT_BAND_LOW_MULTIPLIER: 0.75,
        PROFIT_BAND_HIGH_MULTIPLIER: 1.25,
        BUY_PRICE_BASE_MULTIPLIER: 0.72,
        BUY_PRICE_SCARCITY_MULTIPLIER: 0.65,
        SELL_PRICE_BASE_MULTIPLIER: 0.70,
        SELL_PRICE_SCARCITY_MULTIPLIER: 1.10,
        RISK_HEAT_DIVISOR: 12,
        ESCORT_COMBAT_DIVISOR: 14,
        ESCORT_TRUST_DIVISOR: 8,
        ESCORT_OPINION_DIVISOR: 25,
        OPEN_TIME_MINUTES: 180,
        OPEN_REPUTATION_GAIN: 3,
        OPEN_TRUST_GAIN: 1,
        OPEN_INFLUENCE_GAIN: 1,
        ESCORT_BASE_COST: 450,
        ESCORT_MIN_COST: 350,
        ESCORT_DEFAULT_COMBAT_RATING: 10,
        ESCORT_COMBAT_COST_MULTIPLIER: 8,
        ESCORT_OPINION_DISCOUNT: 4,
        ESCORT_HIRE_TIME_MINUTES: 45,
        ESCORT_HIRE_OPINION_GAIN: 4,
        ESCORT_HIRE_TRUST_GAIN: 2,
        ESCORT_HIRE_DEBT_GAIN: 1,
        STARVED_PAUSE_DAYS: 3,
        STARVED_RELIABILITY_LOSS: 3,
        FAILURE_MIN_CHANCE: 0.02,
        FAILURE_MAX_CHANCE: 0.55,
        FAILURE_BASE_CHANCE: 0.04,
        FAILURE_RISK_MULTIPLIER: 0.035,
        FAILURE_ESCORT_MULTIPLIER: 0.025,
        FAILURE_RELIABILITY_MULTIPLIER: 0.003,
        FAILURE_HEAT_BASE: 3,
        FAILURE_RELIABILITY_LOSS: 8,
        FAILURE_PIRATE_THREAT_CAP: 6,
        SUCCESS_HEAT_LOSS: 1,
        SUCCESS_RELIABILITY_GAIN: 2,
        SUCCESS_RELIABILITY_ADJUSTMENT_DIVISOR: 4,
        ESCORT_RELATION_RUN_INTERVAL: 3,
        ESCORT_RELATION_OPINION_GAIN: 2,
        ESCORT_RELATION_TRUST_GAIN: 1,
        SMUGGLER_SIDE_BUSINESS_CHANCE: 0.15,
        SMUGGLER_SIDE_BUSINESS_HEAT: 2
    },
    LOGISTICS_OBJECTIVE: LOGISTICS_OBJECTIVE_BALANCE,
COMBAT: {
        EMERGENCY_REPAIR_CREDIT_MULTIPLIER: 0.75,
        PIRATE_FIGHT_MIN_FIGHTERS: 10,
        PIRATE_FIGHT_TIME_MINUTES: 60,
        VC_SOFTENING_DIVISOR: 1000,
        FIGHTER_LOSS_BASE: 3,
        FIGHTER_LOSS_RANDOM_BASE: 8,
        FIGHTER_LOSS_THREAT_MULTIPLIER: 4,
        SHIELD_DAMAGE_BASE: 10,
        SHIELD_DAMAGE_RANDOM_BASE: 12,
        SHIELD_DAMAGE_THREAT_MULTIPLIER: 8,
        SHIELD_DAMAGE_SOFTENING_DIVISOR: 2,
        PIRATE_REWARD_BASE: 250,
        PIRATE_REWARD_THREAT_MULTIPLIER: 350,
        PIRATE_REWARD_RANDOM: 300,
        PIRATE_INTEL_CHANCE: 0.25,
        PIRATE_INTEL_VALUE_BASE: 30,
        PIRATE_INTEL_VALUE_THREAT_MULTIPLIER: 5,
        PIRATE_INTEL_EXPIRY_DAYS: 7
    },
    TRAVEL: {
        PIRATE_INCIDENT_BASE_CHANCE: 0.08,
        PIRATE_INCIDENT_MAX_CHANCE: 0.35,
        SDA_INCIDENT_MULTIPLIER: 0.65,
        VC_RECOGNITION_REP_THRESHOLD: 50,
        VC_INCIDENT_MULTIPLIER: 0.55,
        PIRATE_DAMAGE_BASE: 8,
        PIRATE_DAMAGE_RANDOM: 15,
        PIRATE_DAMAGE_THREAT_MULTIPLIER: 2,
        VC_LEVERAGE_CHANCE: 0.30
    },
    MINING: {
        OPERATION_TIME_MINUTES: 120,
        YIELD_RANDOM_MIN: 0.80,
        YIELD_RANDOM_SPREAD: 0.40,
        HC_INFLUENCE_YIELD_MULTIPLIER: 1.08,
        VC_INFLUENCE_YIELD_MULTIPLIER: 1.03,
        DEFAULT_INFLUENCE_YIELD_MULTIPLIER: 1.0,
        MIN_HAZARD_CHANCE: 0.01,
        HAZARD_DAMAGE_BASE: 6,
        HAZARD_DAMAGE_RANDOM: 22,
        SURVEY_MIN_MINUTES: 35,
        SURVEY_BASE_MINUTES: 60,
        SURVEY_INTEL_BASE_CHANCE: 0.45,
        SURVEY_INTEL_MAX_CHANCE: 0.85,
        FRONT_SUSPICION_GAIN: 12,
        FRONT_SUSPICION_MAX: 100,
        FRONT_INTEL_VALUE_BASE: 35,
        FRONT_INTEL_EXPIRY_DAYS: 8
    },
    MARKET: MARKET_BALANCE,
ROUTE_PLANNER: {
        DEFAULT_STABILITY: 100,
        CLOSED_STATUS: "closed",
        DEPLETED_RESERVE_COST: 4,
        MAX_RESERVE_PRESSURE_COST: 4,
        BADLANDS_RISK_BONUS: 1,
        VC_RISK_BONUS: 1,
        SDA_RISK_REDUCTION: 1,
        SECTOR_RISK_MULTIPLIER: 1.5,
        MIN_SPAN_COST: 0.1,
        TOLL_DIVISOR: 100,
        STABILITY_PENALTY_DIVISOR: 25,
        DESTINATION_RESERVE_COST_MULTIPLIER: 0.5,
        BASE_EDGE_COST: 1
    },
    AMBIENT_TRADE: {
        MAX_SEARCH_DISTANCE: 5,
        MAX_DAILY_FILL_SHARE: 0.28,
        MAX_DAILY_EXPORT_SHARE: 0.18,
        BASE_FLOW: 22,
        DISTANCE_PENALTY: 0.45,
        RISK_PENALTY: 0.28,
        RISK_REJECTION_THRESHOLD: 6,
        JITTER: 0.18,
        MIN_MARGIN: 10,
        NODE_TARGETS: {
            SELLER_SURPLUS_FLOOR: 0.25,
            NONSELLER_SURPLUS_FLOOR: 0.55,
            BUYER_SHORTAGE_TARGET: 0.62,
            NONBUYER_SHORTAGE_TARGET: 0.35
        },
        DEFAULT_MAX_STOCK_CAP: 9999,
        DISTANCE_BASELINE: 1
    },
    ECONOMY: {
        TARGET_STOCK_RATIO: 0.45,
        SHORTAGE_PRICE_MULTIPLIER: 0.85,
        SURPLUS_PRICE_DISCOUNT: 0.35,
        EXTRACTION_SCALE: 0.09,
        PRICE_CALIBRATION: {
            MAX_ROUTE_RISK: 8,
            MAX_ROUTE_HOPS: 8
        },
        SPATIAL_PRICE_RELAXATION: {
            DISTANCE_WEIGHT_MULTIPLIER: 0.8,
            RISK_WEIGHT_MULTIPLIER: 0.6,
            MAX_HOPS: 8
        },
        CONTRACTS: {
            MIN_AMOUNT: 8,
            BASE_AMOUNT: 10,
            AMOUNT_PRESSURE_MULTIPLIER: 30,
            LIFESPAN_DAYS: 4,
            MAX_ACTIVE: 18,
            GENERATION_SHORTAGE_THRESHOLD: 0.35,
            PRESSURE_REDUCTION_PER_UNIT: 0.01,
            EMBARGO_ROUTE_ACCESS_THRESHOLD: 0.2,
            SURPLUS_EXPORT_RATIO_THRESHOLD: 2,
            PURCHASE_ORDER_DEMAND_RATIO_THRESHOLD: 1.2,
            SHORTAGE_RELIEF_SEVERITY_THRESHOLD: 0.4,
            PREMIUM_MIN_RATE: 0.08,
            PREMIUM_MAX_RATE: 0.42,
            SHORTAGE_PREMIUM_MULTIPLIER: 0.22,
            URGENCY_PREMIUM_MULTIPLIER: 0.14,
            ROUTE_RISK_PREMIUM_MULTIPLIER: 0.18,
            CRITICAL_PULSE_PREMIUM_BONUS: 0.08,
            BLACK_MARKET_PREMIUM_BONUS: 0.07,
            MAX_DAILY_CONTRACT_PREMIUM_PAYOUT: 200000
        }
    },
    CAPTAIN_ROUTE: {
        EVALUATION_INTERVAL_DAYS: 3,
        MIN_MARGIN: 16,
        MAX_OWNED_ROUTES: 2,
        BAD_ROUTE_FAILURES: 4
    },
    CONTRABAND: {
        RECEIVER_FACTION_ID: "vc",
        INSPECTOR_FACTION_ID: "sda",
        BASE_HIDDEN_HOLD_FRACTION: 0.18,
        MIN_HIDDEN_HOLD_CAPACITY: 4,
        SCANNER_HIDDEN_HOLD_BONUS: 1,
        SMUGGLER_TIER_HIDDEN_HOLD_BONUS: 2,
        BADLANDS_SOURCE_BONUS: 12,
        RECEIVER_SOURCE_BONUS: 25,
        RECEIVER_DEMAND_BONUS: 35,
        PIRATE_SOURCE_MULT: 7,
        PIRATE_DEMAND_MULT: 5,
        SDA_SOURCE_PRESSURE_MULT: 0.25,
        VC_DEMAND_MULT: 0.7,
        SOURCE_QUANTITY_DIVISOR: 18,
        DEMAND_QUANTITY_DIVISOR: 16,
        INSPECTION_BASE_CHANCE: 0.08,
        INSPECTION_MIN_CHANCE: 0.03,
        INSPECTION_MAX_CHANCE: 0.85,
        INSPECTION_HEAT_MULT: 0.015,
        INSPECTION_SCANNER_MITIGATION: 0.04,
        INSPECTION_FORGED_MITIGATION_CAP: 0.12,
        INSPECTION_FACTION_HEAT_PRESSURE: 0.0025,
        INSPECTION_SDA_INFLUENCE_PRESSURE: 0.0015,
        INSPECTION_PIRATE_NOISE: 0.01,
        ROUTE_RISK_REWARD_MULT: 0.04,
        ROUTE_RISK_REWARD_CAP: 0.5,
        DEMAND_REWARD_DIVISOR: 80,
        DEMAND_REWARD_CAP: 0.3,
        RELATIONSHIP_REWARD_DIVISOR: 2500,
        RELATIONSHIP_REWARD_CAP: 0.12,
        PICKUP_MIN_REP: 1,
        PICKUP_REP_DIVISOR: 5,
        PICKUP_TRUST_GAIN: 1,
        DELIVERY_MIN_REP: 2,
        DELIVERY_REP_DIVISOR: 3,
        DELIVERY_TRUST_GAIN: 2,
        MAX_BUST_HEAT: 25,
        BUST_BASE_HEAT: 5,
        ENFORCEMENT_WARNING_HEAT: 10,
        ENFORCEMENT_WARRANT_HEAT: 20,
        ENFORCEMENT_PURSUIT_HEAT: 45,
        ENFORCEMENT_RECENT_BUST_DAYS: 7,
        MAX_BUST_REP_LOSS: 8,
        MAX_DELIVERY_HEAT: 10,
        DELIVERY_BASE_HEAT: 1,
        DELIVERY_HEAT_DIVISOR: 4,
        ACQUIRED_EVENT_IMPORTANCE: 2,
        BUST_EVENT_IMPORTANCE: 4,
        DELIVERED_EVENT_IMPORTANCE: 3,
        TYPES: {
            black_market_eq: {
                id: "black_market_eq",
                name: "Black-Market Equipment",
                value: 220,
                heat: 4,
                bulk: 1,
                sourceWeight: { industrial: 3, refinery: 2, stardock: 1 },
                demandWeight: { mining: 2, agricultural: 1, consumer: 2 }
            },
            forged_manifests: {
                id: "forged_manifests",
                name: "Forged Manifests",
                value: 140,
                heat: 2,
                bulk: 1,
                inspectionMitigation: 0.03,
                sourceWeight: { stardock: 3, consumer: 2, refinery: 1 },
                demandWeight: { industrial: 2, mining: 1, agricultural: 1 }
            },
            restricted_meds: {
                id: "restricted_meds",
                name: "Restricted Meds",
                value: 180,
                heat: 3,
                bulk: 1,
                sourceWeight: { agricultural: 2, consumer: 2, stardock: 1 },
                demandWeight: { mining: 2, refinery: 2, industrial: 1 }
            }
        }
    },
    FRONT_EXPOSURE_THRESHOLD: 88,
    FACTION_EXPANSION_MIN_INFLUENCE: 68,
    POLITICAL_INTEL_BASE_CHANCE: 0.06,
    POLITICAL_MISSION_LIMIT: 14,
    CONTESTED_GAP: 8,
    WORLD_EVENT_LIMIT: 90,
    NOTIFICATION_LIFETIME_MS: 8000,
    MAX_NOTIFICATIONS: 5,
    PRIORITY_FEED_LIMIT: 8,
    LEGACY_SECTOR_COUNT: 30,
    SECTOR_COUNT: 60,
    WORLDGEN: {
        DEFAULT_OCCUPIED_SITES: 240,
        SITE_COUNT_PRESETS: [180, 240, 360, 540, 720],
        MAX_OCCUPIED_SITES: 720,
        DEFAULT_ARCHETYPE: "barred_spiral",
        DEFAULT_ROUTE_DENSITY: 1.0,
        DEFAULT_CHARTED_FRACTION: 0.28,
        DEFAULT_REACHABLE_CHARTED_FRACTION: 0.75,
        WAY_STATION_MAX_FRACTION: 0.08,
        SITE_TYPE_MIX: {
            stellar_system: 0.62,
            brown_dwarf_system: 0.14,
            circumbinary_system: 0.06,
            multiple_star_system: 0.07,
            rogue_system: 0.04,
            white_dwarf_remnant: 0.02,
            way_station: 0.04,
            exotic_remnant: 0.01
        },
        RICHNESS_MIX: {
            barren: 0.18,
            sparse: 0.24,
            developing: 0.22,
            settled: 0.20,
            hub: 0.10,
            strategic: 0.06
        },
        ARCHETYPES: {
            barred_spiral: { name: "Barred Spiral", armCount: 2, clusterJitter: 2.6, zScale: 2.8, barLength: 22, armSpacing: 4.8, armTwist: 0.22 },
            four_arm_spiral: { name: "Four-Arm Spiral", armCount: 4, clusterJitter: 2.4, zScale: 3.2, armSpacing: 5.3, armTwist: 0.19, satelliteEvery: 9 },
            ring_spiral: { name: "Ring Spiral", armCount: 3, clusterJitter: 2.8, zScale: 3.0, ringRadius: 24, armSpacing: 4.4, armTwist: 0.17 },
            dwarf_irregular: { name: "Dwarf Irregular", armCount: 0, clusterJitter: 4.2, zScale: 4.5, chainDrift: 2.6 }
        }
    },
    GATE_PHYSICS: {
        VACUUM_SPAN: 6.0,
        SHEAR_AVG_MULT: 0.35,
        SHEAR_PEAK_MULT: 0.20,
        ROUTE_SURCHARGE_BY_WAY_STATIONS: [0, 0.08, 0.25, 0.60, 1.20],
        ENERGY: {
            CREDIT_PER_TJ: 1,
            REFERENCE_SHIP_PRICE: 100,
            REFERENCE_APERTURE_DIAMETER_M: 4,
            REFERENCE_HOLD_SECONDS: 12,
            SOURCE_BASE_TJ: 4.0,
            SOURCE_RANGE_MULT: 1.6,
            SOURCE_DIAMETER_EXPONENT: 2.4,
            SOURCE_HOLD_GRACE_SECONDS: 18,
            SOURCE_HOLD_EXP_SECONDS: 22,
            ANCHOR_BASE_TJ: 0.8,
            ANCHOR_RANGE_MULT: 0.4,
            ANCHOR_DIAMETER_EXPONENT: 1.2,
            ANCHOR_HOLD_GRACE_SECONDS: 18,
            ANCHOR_HOLD_EXP_SECONDS: 40
        },
        WAY_STATION: {
            BASELINE_POWER_CREDITS_PER_HOUR: 0.02,
            ORDINARY_RESERVE_MIN: 18,
            ORDINARY_RESERVE_MAX: 36,
            FRONTIER_RESERVE_MIN: 40,
            FRONTIER_RESERVE_MAX: 60,
            SERVICE_HOURS_BY_CHAIN_LENGTH: [0, 12, 24, 48, 96],
            RESERVE_STATE_THRESHOLDS: { full: 0.90, stable: 0.65, strained: 0.40, low: 0.15 }
        },
        PULSE_CARGO: {
            pulse_canister: { name: "Pulse Canister", storedTJ: 5, basePrice: 7 },
            heavy_pulse_module: { name: "Heavy Pulse Module", storedTJ: 20, basePrice: 26 }
        },
        ACCUMULATORS: {
            NAME: "Metric Pulse Accumulator",
            CAPACITY_BANDS_TJ: [12, 24, 48, 96, 192, 320],
            PRACTICAL_UPPER_TJ: 320
        }
    },
    PRICE: {
        REP_DIVISOR: 3000,
        PRIVATE_DIVISOR: 7000,
        TRUST_DIVISOR: 2500,
        HEAT_DIVISOR: 1800,
        INFLUENCE_DIVISOR: 2500,
        TRADER_GUILD_BONUS: 0.025,
        AFFINITY_GUILD_BONUS: 0.015,
        MAX_BONUS: 0.35,
        MAX_PENALTY: 0.25,
        MIN_MULT: 0.68,
        MAX_MULT: 1.40
    },
    FIGHTER_COST: 80,
    REPAIR_SHIELD_COST: 2,
    REPAIR_HULL_COST: 35,
    DATA_CARGO: {
        PUBLIC_MAX_SNAPSHOTS_PER_SECTOR: 24,
        PUBLIC_COLD_AFTER_DAYS: 9,
        PUBLIC_STALE_AFTER_DAYS: 5,
        PUBLIC_AGING_AFTER_DAYS: 2,

        PRIVATE_BASE_VALUE: 35,
        PRIVATE_MAX_PLAYER_PAYLOADS: 8,
        PRIVATE_DEFAULT_EXPIRY_DAYS: 8,
        PRIVATE_SALE_MIN_REP_GAIN: 1,
        PRIVATE_SALE_VALUE_REP_DIVISOR: 25,
        PRIVATE_SALE_TRUST_GAIN: 1,
        PRIVATE_GENERATION_CHANCE: 0.12,
        PRIVATE_VALUE_RANDOM_SPAN: 26,
        PRIVATE_EXPIRY_RANDOM_DAYS: 2,

        SECURE_BASE_VALUE: 120,
        SECURE_MAX_ACTIVE_PAYLOADS: 3,
        SECURE_DEFAULT_EXPIRY_DAYS: 7,
        SECURE_INTERCEPTION_BASE_CHANCE: 0.03,
        SECURE_LICENSE_REP_THRESHOLD: 45,
        SECURE_LICENSE_TRUST_THRESHOLD: 25,
        SECURE_MAX_AVAILABLE_CONTRACTS: 8,
        SECURE_GENERATION_SECTOR_DIVISOR: 4,
        SECURE_GENERATION_SKIP_CHANCE: 0.45,
        SECURE_RISK_MIN: 1,
        SECURE_RISK_MAX: 5,
        SECURE_RISK_RANDOM_SPAN: 3,
        SECURE_RISK_PIRATE_DIVISOR: 3,
        SECURE_VALUE_PER_RISK: 35,
        SECURE_VALUE_RANDOM_SPAN: 55,
        SECURE_EXPIRY_RANDOM_DAYS: 2,
        SECURE_DELIVERY_MIN_REP_GAIN: 2,
        SECURE_DELIVERY_VALUE_REP_DIVISOR: 50,
        SECURE_DELIVERY_LOGISTICS_AMOUNT_DIVISOR: 100,
        SECURE_DELIVERY_TRUST_GAIN: 2,
        SECURE_HANDOFF_TRUST_GAIN: 1,
        SECURE_EXPIRY_REP_LOSS: 1,
        SECURE_HOSTILE_FACTION_ID: "vc",
        SECURE_HOSTILE_PRESSURE: 0.04,
        SECURE_INTERCEPTION_RISK_MULTIPLIER: 0.025,
        SECURE_INTERCEPTION_PIRATE_MULTIPLIER: 0.015,
        SECURE_INTERCEPTION_MAX_CHANCE: 0.28,
        SECURE_WARNING_OUTCOME_THRESHOLD: 0.25,
        SECURE_DAMAGE_OUTCOME_THRESHOLD: 0.55,
        SECURE_COMPROMISE_OUTCOME_THRESHOLD: 0.85,
        SECURE_DAMAGE_BASE: 4,
        SECURE_DAMAGE_RANDOM_SPAN: 10,
        SECURE_COMPROMISE_REP_LOSS: 2,
        AMBIENT_TRANSFER_LOG_LIMIT: 50,

        STALE_SIGNAL_MIN_AGE_DAYS: 6,
        STALE_SIGNAL_REWARD_BASE: 180,
        STALE_SIGNAL_REWARD_PER_HOP: 45,
        STALE_SIGNAL_REWARD_AGE_BONUS: 15,
        STALE_SIGNAL_EXPIRY_DAYS: 10
    },
    BOUNTIES: {
        REWARD_FLOOR: 500,
        REWARD_MULTIPLIER_HEAT: 40,
        EXPIRY_MIN_DAYS: 2,
        EXPIRY_MAX_DAYS: 14,
        EXPIRY_DEFAULT_DAYS: 6,
        VISIBILITY_CAP: 40,
        CLAIM_REP_GAIN: 4,
        DUPLICATE_WINDOW_DAYS: 7,
        HUNTER_PRESSURE_HEAT_THRESHOLD: 20,
        VALIDATION: {
            MIN_REWARD: 100,
            MAX_REWARD: 200000
        }
    },
    BOUNTY_GUILDS: [
        { id: 'sda_marshal', name: 'SDA Marshal Compact', sponsorFactionIds: ['sda'], rivalGuildIds: ['free_hands_union'], baseFee: 0.12, legalMethods: ['defeat', 'capture'], minimumTierRules: { warrant: 1 }, claimEvidenceRules: ['combat_log', 'transponder_ping'], defaultRecognitionProfile: ['sda', 'fu'] },
        { id: 'free_hands_union', name: 'Free Hands Union', sponsorFactionIds: ['fu'], rivalGuildIds: ['sda_marshal', 'frontier_wardens'], baseFee: 0.08, legalMethods: ['defeat', 'capture'], minimumTierRules: { private_contract: 1 }, claimEvidenceRules: ['combat_log'], defaultRecognitionProfile: ['fu', 'hc'] },
        { id: 'helios_reclaimers', name: 'Helios Reclaimers', sponsorFactionIds: ['hc'], rivalGuildIds: ['void_retribution'], baseFee: 0.09, legalMethods: ['capture'], minimumTierRules: { pirate_suppression: 2 }, claimEvidenceRules: ['biometric_scan', 'combat_log'], defaultRecognitionProfile: ['hc'] },
        { id: 'frontier_wardens', name: 'Frontier Wardens', sponsorFactionIds: ['colonists'], rivalGuildIds: ['free_hands_union'], baseFee: 0.07, legalMethods: ['defeat', 'capture'], minimumTierRules: { warrant: 1 }, claimEvidenceRules: ['witness_affidavit'], defaultRecognitionProfile: ['colonists', 'fu'] },
        { id: 'oreline_recovery', name: 'Oreline Recovery Office', sponsorFactionIds: ['miners'], rivalGuildIds: ['void_retribution'], baseFee: 0.1, legalMethods: ['capture'], minimumTierRules: { cargo_theft: 2 }, claimEvidenceRules: ['manifest_hash', 'combat_log'], defaultRecognitionProfile: ['miners', 'hc'] },
        { id: 'void_retribution', name: 'Void Retribution League', sponsorFactionIds: ['traders'], rivalGuildIds: ['helios_reclaimers', 'oreline_recovery'], baseFee: 0.11, legalMethods: ['defeat'], minimumTierRules: { pirate_suppression: 1 }, claimEvidenceRules: ['combat_log', 'wreck_signature'], defaultRecognitionProfile: ['traders', 'fu'] },
        { id: 'captain_compact', name: 'Captain Compact Registry', sponsorFactionIds: ['fu', 'colonists'], rivalGuildIds: ['sda_marshal'], baseFee: 0.06, legalMethods: ['defeat', 'capture'], minimumTierRules: { frontier_vendetta: 1 }, claimEvidenceRules: ['captain_attestation'], defaultRecognitionProfile: ['fu', 'colonists', 'traders'] }
    ]
};

export const COMMODITIES = MARKET_COMMODITIES;

export { COMMODITY_REGISTRY, getCommodityDef, getCommodityIdsByCategory, RAW_COMMODITIES, PROCESSED_COMMODITIES, MANUFACTURED_COMMODITIES, PULSE_COMMODITIES, MARKET_COMMODITIES, CARGO_COMMODITIES, COMMODITY_NAMES, COMMODITY_BASE_PRICES };
