export const POLITICS = Object.freeze({
    CONTESTED: Object.freeze({
        MIN_FACTION_SPREAD: 2,
        PIRATE_SURGE_CAP: 6,
        PIRATE_SURGE_BASE_CHANCE: 0.14,
        PIRATE_SURGE_DAILY_CHANCE: 0.015,
        PIRATE_REDUCTION_CHANCE: 0.22,
        SDA_REDUCTION_BASE_CHANCE: 0.18,
        SDA_REDUCTION_REP_DIVISOR: 4000,
        MISSION_BASE_CHANCE: 0.18,
        MISSION_DAILY_CHANCE: 0.01,
        MISSION_SPONSOR_TOP_CHANCE: 0.58
    }),
    SECTOR_EFFECTS: Object.freeze({
        SDA_THRESHOLD: 55,
        SDA_MAX_REDUCTION_CHANCE: 0.45,
        SDA_CHANCE_OFFSET: 45,
        SDA_CHANCE_DIVISOR: 130,
        HC_THRESHOLD: 55,
        HC_REGEN_BASE: 12,
        HC_REGEN_PER_INFLUENCE: 0.65,
        HC_REGEN_RATE: 0.035,
        HC_MIN_MAX_ORE: 2500,
        FU_THRESHOLD: 55,
        FU_GROWTH_CHANCE: 0.28,
        FU_COLONIST_GROWTH_RATE: 0.04,
        VC_PIRATE_THRESHOLD: 50,
        VC_PIRATE_MAX_CHANCE: 0.32,
        VC_PIRATE_CHANCE_OFFSET: 40,
        VC_PIRATE_CHANCE_DIVISOR: 150,
        VC_PIRATE_CAP: 6,
        VC_FRONT_THRESHOLD: 58,
        VC_FRONT_CHANCE: 0.055,
        VC_FRONT_SUSPICION_BASE: 12,
        VC_FRONT_SUSPICION_SPAN: 18
    }),
    FRONTS: Object.freeze({
        SUSPICION_BASE_GAIN: 1,
        SUSPICION_INFLUENCE_DIVISOR: 30,
        INITIAL_SUSPICION_BASE: 10,
        INITIAL_SUSPICION_SPAN: 15,
        SURVEYED_SUSPICION_GAIN: 1,
        PIRATE_THREAT_SUSPICION_THRESHOLD: 3,
        PIRATE_THREAT_SUSPICION_GAIN: 1,
        HIDDEN_ADVANTAGE_THRESHOLD: 20,
        SURVEYED_BONUS: 2,
        UNSURVEYED_PENALTY: -1,
        PUBLIC_ADVANTAGE_CHANCE: 0.45,
        PUBLIC_ADVANTAGE_REDUCTION: 1,
        SURVEYED_EXPOSURE_CHANCE: 0.68,
        UNSURVEYED_EXPOSURE_CHANCE: 0.38,
        HIDDEN_INFLUENCE_ON_EXPOSED: -9,
        PUBLIC_INFLUENCE_ON_EXPOSED: 4,
        SDA_INFLUENCE_ON_VC_EXPOSED: 2,
        RELATION_ON_EXPOSED: -3,
        EVENT_IMPORTANCE: 4
    }),
    EXPANSION: Object.freeze({
        SOURCE_THRESHOLD: 58,
        CHANCE_DIVISOR: 260,
        SDA_CORE_BONUS: 0.025,
        FU_FRONTIER_BONUS: 0.035,
        HC_ASTEROID_BONUS: 0.025,
        VC_BADLANDS_BONUS: 0.055,
        CONTESTED_TARGET_BONUS: 0.035,
        MAX_CHANCE: 0.32,
        OWNED_TARGET_INFLUENCE_FLOOR: 72,
        STRONG_INFLUENCE_THRESHOLD: 82,
        STRONG_GAIN: 2,
        NORMAL_GAIN: 1
    }),
    INTEL: Object.freeze({
        INTERESTING_PIRATE_THREAT: 3,
        MAX_CHANCE: 0.34,
        REP_DIVISOR: 3500,
        TRUST_DIVISOR: 700,
        CURRENT_SECTOR_BONUS: 0.08,
        NEARBY_SECTOR_BONUS: 0.03,
        VALUE_BASE: 25,
        VALUE_SPAN: 20,
        EXPIRES_DAYS: 5
    }),
    FACTION_DRIFT: Object.freeze({
        HEAT_DECAY_CHANCE: 0.45,
        LEVERAGE_DECAY_CHANCE: 0.12,
        GUILD_TRUST_DECAY_CHANCE: 0.08,
        SDA_FINE_HEAT_THRESHOLD: 70,
        SDA_FINE_CHANCE: 0.35,
        SDA_FINE_BASE: 400,
        SDA_FINE_SPAN: 900,
        SDA_FINE_HEAT_REDUCTION: -12,
        SDA_FINE_LEVERAGE_GAIN: 2,
        RELATION_NEWS_CHANCE: 0.30,
        RELATION_PAIR_SPLIT_CHANCE: 0.5,
        RELATION_DELTA_SPLIT_CHANCE: 0.5,
        CORE_PIRATE_PROBE_CHANCE: 0.10,
        CORE_PIRATE_PROBE_CAP: 4
    }),
    PORT_ECONOMY: Object.freeze({
        SELLER_REFILL_BASE: 0.06,
        SELLER_REFILL_SPAN: 0.05,
        BUYER_CONSUMPTION_BASE: 0.03,
        BUYER_CONSUMPTION_SPAN: 0.04
    }),
    THREATS: Object.freeze({
        BADLANDS_BASE_CHANCE: 0.22,
        FRONTIER_BASE_CHANCE: 0.12,
        SDA_CHANCE_MODIFIER: -0.06,
        FU_CHANCE_MODIFIER: -0.02,
        VC_CHANCE_MODIFIER: 0.07,
        DEFENSE_CHANCE_MODIFIER: -0.04,
        CARTEL_PROTECTION_MODIFIER: -0.05,
        SDA_PATROL_MODIFIER: -0.06,
        MIN_CHANCE: 0.02,
        PIRATE_THREAT_CAP: 6
    }),
    CONTEST_MISSIONS: Object.freeze({
        EXPIRES_DAYS: 4,
        REWARD_REP: 3,
        PIRATE_THREAT_REWARD: 220,
        SECTOR_REWARD: 12,
        TEMPLATES: Object.freeze({
            sda: Object.freeze({ verb: "Run patrol pressure", operation: "patrol", minutes: 90, reward: 1900 }),
            fu: Object.freeze({ verb: "Rally frontier support", operation: "rally", minutes: 75, reward: 1750 }),
            hc: Object.freeze({ verb: "Secure industrial claims", operation: "claims", minutes: 90, reward: 2050 }),
            vc: Object.freeze({ verb: "Disrupt official control", operation: "disrupt", minutes: 75, reward: 2200 })
        })
    })
});
